#!/usr/bin/env bash

usage() {
    echo -e "List ${SCPT_NAME} example sessions with short description"
    echo -e 'or show the contents of one.'
    echo -e "Usage: ${SCPT_NAME} examples [EXAMPLENAME]"
}

[ "$1" = "--help" ] && usage && exit 0

source "${YATSH_ROOT}/lib/global_helpers.sh"

_list_examples() {
    _set_opt nullglob
    for example in "$YATSH_ROOT/examples"/*; do
        echo -e "${Y}$(basename $example)${RESET} # -- $(_extract 'DESCRIPTION' $example)"
    done
    _unset_opt nullglob
}

if [ $# -ge 1 ]; then
    SESSION=$1; shift
    _echo_example_file $SESSION && exit 0
fi

[ $? -gt 0 ] && echo 'Session not found'

_list_examples | column -t -s'#'
