#!/usr/bin/env bash

usage(){
    echo -e "Usage: ${SCPT_NAME} new SESSION [-l] [-e EXAMPLE]"
    echo -e 'Create a session file optionally from a predefined example.'
    echo
    echo -e 'Available options:'
    echo -e "${TAB}${Y}-l         ${RESET} -- Create session file in current directory."
    echo -e "${TAB}${Y}-e EXAMPLE ${RESET} -- Use example session file."
}

[ "$1" = "--help" -o $# -lt 1 ] && usage && exit 0

source "${YATSH_ROOT}/lib/global_helpers.sh"

session_name=$1; shift
while getopts ':le:' option; do
    case "$option" in
        e) example_name=$OPTARG ;;
        l) local_session=true ;;
        *) echo "Invalid option" ; usage ; exit 1 ;;
    esac
done

if [ "$local_session" ]; then
    session_file="$(pwd)/${session_name}"
else
    session_file="${YATSH_SESSIONS_DIR}/${session_name}"
fi

example_session=$(_echo_example_file $example_name || _echo_example_file 'main')

# EDITOR not explicitly set or uses vim
if [[ -z $EDITOR || $EDITOR =~ 'vi' ]] ; then
    # create a buffer with dummy content in $TMUXSTART_DIR
    echo "$example_session" | ${EDITOR:-vi} - "+file $session_file"\
        "+set pvh=80" \
        "+let &fen=0" \
        "+set shm=at" \
        "+set ch=2" \
        "+vert ped ${YATSH_ROOT}/lib/session_helpers.sh"
else
    echo "$example_session" > $session_file && $EDITOR $session_file
fi
