#!/usr/bin/env bash

[ $# -lt 1 ] && echo "Not enough arguments" && exit 1

SESSION=$1

source "${YATSH_ROOT}/lib/session_helpers.sh"

TMUX_OLD=$TMUX
TMUX=
if ! tmux has-session -t $SESSION 2> /dev/null ; then
    # local sessions first
    if [ -f "${PWD}/${SESSION}" ]; then
        . "${PWD}/${SESSION}"
    else
        # globally available local sessions next
        if [ -h "${YATSH_DIR}/sessions/$SESSION" ]; then
            cd $(dirname $(readlink "${YATSH_DIR}/sessions/$SESSION"))
            . "$SESSION"
        else
            [ -f "${YATSH_DIR}/sessions/$SESSION" ] && . "${YATSH_DIR}/sessions/$SESSION"
        fi
        tmux new-session -d -s $SESSION
    fi
fi
if [ "$TMUX_OLD" = "" ]; then
    tmux attach-session -t $SESSION
else
    tmux switch-client -t $SESSION
fi
TMUX=$TMUX_OLD
