#!/usr/bin/env bash

usage(){
    echo -e "${SCPT_NAME} new SESSION [-l] [-e EXAMPLE]"
}
[ "$1" = "--help" -o $# -lt 1 ] && usage && exit 0
. "${YATSH_ROOT}/lib/global_helpers.sh"

session_name=$1; shift
while getopts ':le:' option; do
    case "$option" in
        e) example_name=$OPTARG ;;
        l) local_session=true ;;
        *) echo "Invalid option" ; usage ; exit 1 ;;
    esac
done
if [ ! "$local_session" ]; then
    session_file="${YATSH_SESSIONS_DIR}/${session_name}"
else
    session_file="$(pwd)/${session_name}"
fi
example_session=$(_echo_example_file $example_name)

# EDITOR not explicitly set or uses vim
if [[ -z $EDITOR || $EDITOR =~ 'vi' ]] ; then
    # create a buffer with dummy content in $TMUXSTART_DIR
    echo "$example_session" | ${EDITOR:-vi} - "+file $session_file"
else
    echo "$example_session" > $session_file && $EDITOR $session_file
fi
