#!/usr/bin/env bash

usage(){
    echo -e "Delete session files."
    echo -e "Usage: ${SCPT_NAME} delete SESSION"
}

[ "$1" = "--help" -o $# -lt 1 ] && usage && exit 0

source "${YATSH_ROOT}/lib/global_helpers.sh"

filename=$1

if _file_exists "${YATSH_SESSIONS_DIR}/${filename}"; then
    echo -e "${Y}[WARNING] Are you sure you want to remove \"$filename\"? [y/N]$RESET"
    read confirm
    [[ $confirm =~ 'y' ]] && echo -e "${R}Removed $(rm -v "${YATSH_SESSIONS_DIR}/${filename}") $RESET" && exit 0
else
    echo -e "${R}[ERROR] Session file for \"$filename\" not found.${RESET}"
fi
exit 1
