#!/usr/bin/env bash

# this plugin should print help for all installed plugins

[ ! $# -gt 0 ] && exec yat.sh --help && return 0

source "${YATSH_ROOT}/lib/global_helpers.sh"

command=$1

if _is_command $command; then
    exec "yatsh-${command}" --help
fi
