#!/usr/bin/env bash

usage(){
    echo -e "${SCPT_NAME} edit [SESSION]"
    echo -e "Edit [local] session file for editing."
}

[ $# -lt 1 ] && echo "Not enough arguments" && exit 1

source "${YATSH_ROOT}/lib/global_helpers.sh"

session_file="${YATSH_DIR}/sessions/$1"

if  _file_exists $session_file; then
    ${EDITOR:-vi} $session_file
else
    echo -e "${R}[ERROR] Session file not found.$RESET"
fi
