#!/usr/bin/env bash

usage() {
    echo 'Link local session file to global directory'
    echo
    echo "Usage: $SCPT_NAME link SESSION"
    echo
    echo 'Once you link a local session file, it will be available from anywhere'
}

[ "$1" = '--help' -o $# -lt 1 ] && usage && exit 0

source=$1 ; shift
link_session_file() {
    if [ -f "./$source" -a ! -f "${YATSH_DIR}/sessions/${source}" ]; then
        ln -s "$PWD/$source" "${YATSH_DIR}/sessions" && exit 0;
    fi
    exit 1
}

link_session_file
