#!/usr/bin/env bash


usage() {
    echo -e "List available session files."
    echo -e "Usage: ${SCPT_NAME} list"
    echo -e "Alias: ${SCPT_NAME} ls"
}

[ "$1" = '--help' ] && usage && exit 0

_print_session_name() {
    local session=$1
    if tmux has-session -t "$session" 2> /dev/null ; then session="$session $G(running)$RESET" ; fi
    echo -e "[-] $session"
}

_list_sessions(){
    shopt -s nullglob
    for file in "${YATSH_DIR}"/sessions/*; do
        _print_session_name $(basename $file)
    done
    shopt -u nullglob
}

_list_sessions | column

