#!/usr/bin/env bash

usage(){
    echo -e "Create deattached tmux session."
    echo -e "Usage: ${SCPT_NAME} SESSION"
}

[ "$1" = "--help" -o $# -lt 1 ] && usage && exit 0

source "${YATSH_ROOT}/lib/global_helpers.sh"
source "${YATSH_ROOT}/lib/session_helpers.sh"

SESSION=$1
DAEMON=$2
TMUX_OLD=$TMUX
TMUX=

_create_session
