#!/usr/bin/env bash

function usage()
{
    echo 'Link local session file to global directory'
    echo
    echo "Usage: $SCPT_NAME link SESSION"
    echo
    echo 'Once you link a local session file, it will be available from anywhere'
}

[ "$1" = '--help' -o $# -lt 1 ] && usage && exit 0

source "${YATSH_ROOT}/lib/global_helpers.sh"

source=$1 ; shift

# TODO: add optional param to set name
if _file_exists "${YATSH_DIR}/sessions/${source}"; then
    _abort "Session file with that name already exists"
fi

if _file_exists ${source} ; then
    _info "Linking ${source} into ${YATSH_DIR}"
    ln -s "$PWD/$source" "${YATSH_DIR}/sessions"
else
    _abort "${source} could not be found."
fi
