#!/usr/bin/env bash

function usage()
{
    echo -e "${SCPT_NAME} edit [SESSION]"
    echo -e "Edit [local] session file for editing."
}

[ $# -lt 1 ] && echo "Not enough arguments" && exit 1

source "${YATSH_ROOT}/lib/global_helpers.sh"

session_name="$1"
session_file="$(_find_session_file "${session_name}")"

if _file_exists $session_file; then
    ${EDITOR:-vi} $session_file
else
    _abort "[ERROR] Session file not found."
fi
