#!/usr/bin/env bash

usage() {
    echo -e "List ${SCPT_NAME} example sessions [with short description]."
    echo -e "Usage: ${SCPT_NAME} example"
}

[ "$1" = "--help" ] && usage && exit 0

source "${YATSH_ROOT}/lib/global_helpers.sh"

_list_examples() {
    _set_opt nullglob
    for example in "$YATSH_ROOT/examples"/*; do
        echo -e "${Y}$(basename $example)${RESET} # -- $(_extract 'DESCRIPTION' $example)"
    done
    _unset_opt nullglob
}

_list_examples | column -t -s'#'
