#!/usr/bin/env bash


usage() {
    echo -e "List available session files."
    echo -e "Usage: ${SCPT_NAME} list"
    echo -e "Alias: ${SCPT_NAME} ls"
    echo
    echo -e 'Available options:'
    echo -e "${TAB}${Y}-a         ${RESET} -- Also list other running tmux sessions."
}

[ "$1" = '--help' ] && usage && exit 0

source "${YATSH_ROOT}/lib/global_helpers.sh"

while getopts ':a' option; do
    case "$option" in
        a) list_all=true ;;
        *) echo "Invalid option" ; usage ; exit 1 ;;
    esac
done

_print_session_name() {
    local session=$1
    if tmux has-session -t "$session" 2> /dev/null; then
        session="$session (running)"
    fi
    echo -e "[-] $session"
}

_non_yatsh_sessions(){
    local sessions=($(tmux list-sessions -F '#S' 2> /dev/null))
    local yatsh_sessions=$(_all_session_names)
    for session in ${yatsh_sessions[*]}; do
        sessions=(${sessions[*]//*$session*})
    done
    echo ${sessions[*]}
}

_list_sessions(){
    local sessions=$1; shift
    for session in ${sessions[*]}; do
        _print_session_name $session
    done
}

echo -e "${G}${SCPT_NAME}${RESET} sessions:"
echo
_list_sessions "$(_all_session_names)" | column

if [ "$list_all" ]; then
    non_yat_sessions=$(_non_yatsh_sessions)
    if [ -n "${non_yat_sessions[*]}" ]; then
        echo
        echo -e 'Other running sessions:'
        echo
        _list_sessions $(_non_yatsh_sessions) | column
    fi
fi

