#!/usr/bin/env bash

usage() {
    echo -e "Start/Attach remote tmux session. "
    echo -e "Usage: ${SCPT_NAME} remote SESSION"
}

[ "$1" = "--help" -o $# -lt 1 ] && usage && exit 0

source "$YATSH_ROOT/lib/global_helpers.sh"

_session_file(){
    sed -e 's/#.*$//' -e '/^$/d' $session_file
}

_session_helpers(){
    sed -e 's/#.*$//' -e '/^$/d' "${YATSH_ROOT}/lib/session_helpers.sh"
}

_remote_session(){
    local remote_session
    remote_session=$(cat $session_file | grep -i '#= NAME:' | cut -d':' -f2)
    [ ! -z "$remote_session" ] && echo $remote_session || echo $session_file
}

session_file="${YATSH_DIR}/sessions/$1"
session_name="$(_remote_session)"

_remote_script(){
    echo "if tmux has-session -t ${session_name} 2> /dev/null ; then"
    echo "tmux attach-session -t ${session_name}"
    echo "else"
    echo "SESSION=${session_name}"
    _session_helpers
    echo "SESSION=${session_name} $(_session_file)"
    echo "tmux attach-session -t ${session_name}"
    echo fi
}

if _file_exists $session_file; then
    server=$(_extract 'SERVER' $session_file)
    remote_script=$(_remote_script)
    if [ ! -z $server ]; then
        ssh $server -t -- "${remote_script}"
    else
        echo -e "${R} No server specified. ${RESET}" && usage && exit 1
    fi
fi

