#!/usr/bin/env bash

# this plugin should print help for all installed plugins

[ ! $# -gt 0 ] && exec yat.sh --help && return 0

COMMAND=$(command -v "yatsh-${1}")

if [ ! -z "$COMMAND" ]; then
    exec $COMMAND --help
fi

