
SCPT_NAME=$(basename $0)
SESSIONS_DIR=${TMUXSTART_DIR:-$HOME/.$SCPT_NAME}
GLOBALS_DIR="$SESSIONS_DIR/globals"
LOCALS_DIR="$SESSIONS_DIR/locals"
EXAMPLES_DIR="$SESSIONS_DIR/examples"
VERSION='[ 0.4.0-alpha ]'

# colors
RESET='\033[0m'
G='\033[0;32m'
Y='\033[0;33m'
R='\033[0;31m'

SESSION=$1
